### ISSUE TITLE
"Get Involved" page - "How you can get involved" tile

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#100]
Who it is for - Volunteers and Potential Volunteers
What it is - A list of the skills that CSC needs to complete projects
Why it matters - Help users determine if/how they fit with the CSC purpose and ongoing projects

List of Skills

- Animation
- Audio Editing
- Business Analysis
- Copywriting
- Data & Visualization
- Data Entry
- Digital Strategy
- Ecommerce
- Epidemiology
- Government Partners
- Graphic Design
- General / Hustle
- Health Partners
- Language - Spanish
- Legal
- Marketing
- Software Engineers
- Students
- Podcasts
- Process Engineering
- Product & Project MGMT
- Real Estate Development
- Technologists
- UX Design & Research

https://projects.invisionapp.com/share/HYWIN5WMQSU#/screens/410295662

**Comment by maharris1011** [comment]
@seanlawrenz is there a PR for this issue/feature? if so, was it already merged & deployed?
