### ISSUE TITLE
"Get Involved" page - "Mission" tile

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#101]
Who it is for - Volunteers and Potential Volunteers
What it is - A description of the CSC purpose
Why it matters - We want a description that inspires our talented Columbus residents to join the cause and contribute to projects

Mission/Purpose - "Can’t Stop Columbus is a community-wide movement that addresses problems that have arisen due to the COVID-19 crisis. Activating our city’s talents and passions, we’re putting bold ideas into action to deliver real solutions that unite our community."

BLOCKED - Language approval from Tobias

https://projects.invisionapp.com/share/HYWIN5WMQSU#/screens/410295662

**Comment by seanlawrenz** [comment]
Issue resolved in [PR-123](https://github.com/maharris1011/cantstopcolumbus/pull/123)
