### ISSUE TITLE
"Get Involved" page - "Teams that need help now" tile

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#103]
Who it is for - Volunteers and Potential Volunteers
What it is - Direct users to Helm page - https://joinhelm.com/org/cant-stop-columbus 
Why it matters - Allows users to review open projects

https://projects.invisionapp.com/share/HYWIN5WMQSU#/screens/410295662

**Comment by seanlawrenz** [comment]
Teams needing help seems to be liquid. How are we going to respond to changes to this page?

**Comment by slythr** [comment]
https://joinhelm.com/org/cant-stop-columbus
