### ISSUE TITLE
"Get Involved" page - Call to Action tile

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#104]
Who it is for - Volunteers and Potential Volunteers
What it is - A call to action that encourages users to volunteers
Why it matters - Drive users to volunteer

https://projects.invisionapp.com/share/HYWIN5WMQSU#/screens/410295662

**Comment by maharris1011** [comment]
Looks like this was resolved with the PR #133 . I'm closing it.

**Comment by maharris1011** [comment]
NVM. i see what's happening now. This was a merge into a feature branch
