### ISSUE TITLE
SPIKE - How will we manage incoming stories?

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#106]
Who it is for - Our team
What it is - We need to understand how we will manage stories from our content developers
Why it matters - Needed to develop the Stories page

FINDINGS - Document below

Notes:
"Real Q. Given the challenges that stories might present (process, speed, editing, access). Should we consider a subdomin that is running something like WordPress? (edited) 

Joshua Hoffman  1:12 PM
I was thinking the same thing @Tobias (Organizer) 

Tobias (Organizer)  1:14 PM
I’m very concerned that our speed to post stories will get very bogged in a manual process. If the site needs a master push just to update an article, we could face downtimes at critical junctures of news cycles
"

**Comment by maharris1011** [comment]
This page has all the information about how to do blogging in Jekyll. [https://jekyllrb.com/docs/step-by-step/08-blogging/](https://jekyllrb.com/docs/step-by-step/08-blogging/) .

The steps are pretty straightforward:
we write a "blog list" page (the one that has the list of stories on it with the excerpts from the stories)
that blog list page has a link to each story
each story is kept under the "_posts" directory with a title like "`yyyy-mm-dd-title.md`", written in markdown (which is like a pigin-HTML)
when we check in the MD file and push to master, it'll get built and published

**Comment by seanlawrenz** [comment]
I'm not excited to convert everything to markdown but this should be our solution.

**Comment by maharris1011** [comment]
It shouldn’t mean everything, just the stories we want to publish

**Comment by maharris1011** [comment]
I found [this site](https://jekyllthemes.io/resources/jekyll-hosting-and-cms-solutions) that has several CMSs built specifically for jekyll static sites. Most of them include hosting, which we don't need. CloudCannon looks good, but it appears that developers still have to be involved. SiteLeaf is promising in that it might actually allow devs to do what devs do, and let editors add blog pages.
@seanlawrenz take a look & let me know what you think?

**Comment by maharris1011** [comment]
closing, since we have stories and an OK method of updating them.
