### ISSUE TITLE
Find help - logo adjustment

### ISSUE THREAD

**Issue by slythr** [maharris1011/cantstopcolumbus#108]
next door munch and ohio means jobs logos are too big

**Comment by maharris1011** [comment]
What size should they be, exactly? they're just filling the space they're given at the moment.

**Comment by slythr** [comment]
@maharris1011 the square icons are roughly 110px^2 in the 200 container.
rectangles are larger. spec here https://projects.invisionapp.com/d/main#/console/19623294/410295174/inspect
