### ISSUE TITLE
"Get Involved" page - header

### ISSUE THREAD

**Issue by slythr** [maharris1011/cantstopcolumbus#12]
Who it is for - Volunteers and Potential Volunteers
What it is - A header with a call to action to join the cause
Why it matters - Drive talented users to join the CSC cause

https://projects.invisionapp.com/share/HYWIN5WMQSU#/screens/410295662

**Comment by seanlawrenz** [comment]
Teams needing help seems to be liquid. How are we going to respond to changes to this page?
