### ISSUE TITLE
SPIKE - Can we randomly load resources to resources "We're getting started" tile on home page?

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#166]
What we will learn: Currently, the "We're just getting started" tile on the home page loads the same four resources. Can we randomly load these resources to provide more visibility to others?

What we will have after card is complete: We will document how we can randomly load resources (if possible) and create a card to complete the work.

**Comment by jranta** [comment]
in short, it could be possible but we're limited to only randomizing it at build time. That means every time we release to the live site a new "random" set would be placed there. Jekyll liquid doesn't have a random tag so it'll be some work doing it. I think the best option is to make it a carousel like it was originally intended.

**Comment by maharris1011** [comment]
we can load them dynamically if we open up an API & call it on load. Shouldn't be too hard. 
are the resources kept in Airtable also?

or... we could do something clever at load time where we re-write the DOM to show different resources. the resources could be stored in JSON statically on the site (or just in the page) and we have a javascript function that decides which 4 to put into the carousel.

**Comment by maharris1011** [comment]
cant-stop-columbus/csc-airtable-api is an api we could open up to pull resources dynamically from the Airtable that CSC is using.
