### ISSUE TITLE
Visual defect - mail icon inverted on "submit a resource"

### ISSUE THREAD

**Issue by slythr** [maharris1011/cantstopcolumbus#211]
low priority
<img width="1191" alt="screen_shot_2020-04-25_at_12 39 28_pm" src="https://user-images.githubusercontent.com/19540786/80316616-c0720f00-87cc-11ea-9a0d-ec9e770775ed.png">

**Comment by maharris1011** [comment]
What do you mean "inverted"? It's bold, like the "Submit a Resource" text. Shouldn't be bold?
