### ISSUE TITLE
SPIKE - How can Users view live CSC content?

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#25]
What we need to learn: Can we embed a live video in the CSC homepage?

Expected outcome: A card that details path forward
- Embedded live video
OR
- Link to live video

FINDINGS: We can embed the video
- add the embed code
- temporarily comment it out
- once they go live, uncomment, plug in the URL and copy only the index.html file to the site through FTP

**Comment by slythr** [comment]
https://developers.facebook.com/docs/plugins/embedded-video-player/
