### ISSUE TITLE
Prepare for embedded video

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#26]
- Add the embed code
- Temporarily comment it out

Title of event - Can’t Stop Columbus Online Rally Live!

**Comment by slythr** [comment]
https://developers.facebook.com/docs/plugins/embedded-video-player/

https://www.facebook.com/cantstopcbus

**Comment by seanlawrenz** [comment]
We've combined a couple of pulls so this should be pointing to https://github.com/maharris1011/cantstopcolumbus/pull/31
