### ISSUE TITLE
Find Help - ODH COVID19 dashboard

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#60]
Add Ohio Dep of Health to help resouces

https://coronavirus.ohio.gov/wps/portal/gov/covid-19/home/dashboard

**Comment by slythr** [comment]
This should be added as a project on the Find help page

**Comment by maharris1011** [comment]
@jthoff10 can I get an ODH logo? The one I copied down from the site is in white, which doesn't show on our background.
