### ISSUE TITLE
Home - Update Columbus of City Icon and link

### ISSUE THREAD

**Issue by jthoff10** [maharris1011/cantstopcolumbus#61]
Current City of Columbus website icon includes "Mayor Coleman" - use SVG in comments

Also link should be
https://coronavirus.ohio.gov/wps/portal/gov/covid-19/

**Comment by slythr** [comment]
[columbus-gov.svg.zip](https://github.com/maharris1011/cantstopcolumbus/files/4390687/columbus-gov.svg.zip)

can't upload file to repo
