### ISSUE TITLE
home - update columbus eats logo

### ISSUE THREAD

**Issue by slythr** [maharris1011/cantstopcolumbus#68]
image in comments

https://projects.invisionapp.com/d/main#/console/19623294/410293687/inspect

**Comment by slythr** [comment]
![support+cbus+eats+(4)](https://user-images.githubusercontent.com/19540786/77715197-538f0d80-6fb1-11ea-8651-d8bcfe08c3de.png)

**Comment by maharris1011** [comment]
updated in branch better-find-help
